services:
    nginx:
        build:
            context: bin/nginx
        container_name: ${CONTAINER_NAME}nginx
        ports:
            - ${PORT_NGINX}:80
        volumes:
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
    php:
        build:
            context: bin/php
        container_name: ${CONTAINER_NAME}php
        volumes:
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    redis:
        build:
            context: bin/redis
        container_name: ${CONTAINER_NAME}redis
        depends_on:
            - php
        restart: always